### ISSUE TITLE
load_image bmp file killing kernel 

### ISSUE THREAD

**Issue by prasad4fun** [fastai/fastcore#119]
[0.zip](https://github.com/fastai/fastcore/files/5351063/0.zip)

while experimenting with fast v2 lib with PILImageBW.create function, load_image function in fast core failing for bmp image file.

im = Image.open("0.bmp") #attached zip version of the file
im.load()
im = im._new(im.im)

im #jupyter kernel dying on this line

Not sure if this is fastcore vs PIL lib issue.

**Comment by jph00** [comment]
Please use the forums for help
