### ISSUE TITLE
Some clarification needed in the definition of `get_class`

### ISSUE THREAD

**Issue by Salehbigdeli** [fastai/fastcore#123]
In notebook `02_utils` there is `get_class` function in order to create classes dynamically. Here is its definition:
`def get_class(nm, *fld_names, sup=None, doc=None, funcs=None, **flds):`
In this definition the last argument `flds` is ambiguous! It's not clear if the author wanted to grab these fields as class attributes or it uses as instance attributes. The code is obviously used it as a class attribute. But tests are confusing!
For example:
```
_t = get_class('_t', 'a', b=2)
t = _t()
test_eq(t.a, None)
test_eq(t.b, 2)
t = _t(1, b=3)
test_eq(t.a, 1)
test_eq(t.b, 3)
```
In this test, it seems that we use `b=2` as an instance attribute since we just used it with the object that we created. But it's not and the field `b` in the first line is different from the `b`  in `t = _t(1, b=3)` the first one is a class attribute and the later is an instance attribute which shadows the class attribute.
See the same example (with a small change to illustrate the issue):
```
_t = get_class('_t', 'a', b=2)
t = _t()
test_eq(t.a, None)
test_eq(t.b, 2)
t = _t(1, b=3)
test_eq(t.a, 1)
test_eq(t.b, 3)
del t.b
test_eq(t.b, 2)
```
This issue is a little more important than just a clarification about one field of a function. Because if accept that the purpose of the `flds` is creating the class attributes, then having `funcs` look obsolete.
You can see this in these two examples:
```
def foo(self): return 1
mk_class('_t', 'a', sup=GetAttr, doc='test doc', funcs=foo)

t = _t(3, b=2)
test_eq(t.a, 3)
test_eq(t.b, 2)
test_eq(t.foo(), 1)
test_eq(t.__doc__, 'test doc')
t
```
and
```
def foo(self): return 1
mk_class('_t', 'a', sup=GetAttr, doc='test doc', foo=foo)

t = _t(3, b=2)
test_eq(t.a, 3)
test_eq(t.b, 2)
test_eq(t.foo(), 1)
test_eq(t.__doc__, 'test doc')
t
```
I can help after the decision has made about this situation.

**Comment by jph00** [comment]
They are indeed class attributes, although in Python a class attr is turned into an instance attr when you construct an instance.

IIRC there's something different about `funcs`... maybe in the repr or something?

**Comment by Salehbigdeli** [comment]
Thanks a lot. I close this issue.
