### ISSUE TITLE
funcs_kwargs doesn't update class signature when inheriting from Module

### ISSUE THREAD

**Issue by lgvaz** [fastai/fastcore#15]
Using `funcs_kwargs` with a class that inherits from `Module` does not update the class signature.

Minimum example:
```python
from fastai2.basics import *

@funcs_kwargs
class C(Module):
  _methods = ['m1']
  def __init__(self, **kwargs): pass
  def m1(self): return 1

print(inspect.signature(C))
```
Returns: `(self, **kwargs)`
Expected: `(*, m1=None)`

**Comment by sgugger** [comment]
Thanks for flagging! Should be fixed now.
