### ISSUE TITLE
log_args function in documentation links to a broken link

### ISSUE THREAD

**Issue by Sandyxuxinxi** [fastai/fastcore#178]
https://fastcore.fast.ai/logargs.html

![image](https://user-images.githubusercontent.com/24632905/98456322-6668f200-21d0-11eb-8bd6-f71a1d3020fc.png)

![image](https://user-images.githubusercontent.com/24632905/98456325-6bc63c80-21d0-11eb-98a7-ad61d9fd1e4b.png)

**Comment by hamelsmu** [comment]
That is because log args is deprecated, we should probably remove this page

**Comment by hamelsmu** [comment]
@jph00 I looked into this, and the only thing I can think of is this is an old page that is not getting deleted because of the `rsync`.  Do you think it makes sense to force overwrite all files in the destination instead of rsync?

**Comment by hamelsmu** [comment]
ok its been removed
