### ISSUE TITLE
Example: storing kwargs with store_attr

### ISSUE THREAD

**Issue by mpariente** [fastai/fastcore#180]
`store_attr` is really cool! 

Passing kwargs to `store_attr` is not explicitely documented, yet, it's a great use case. 
Should I make a PR to add this to the notebook? 

```python
class T:
    def __init__(self, a,b,c,**kwargs): store_attr(**kwargs)

t = T(1,c=2,b=3,d=4,e=-1)
assert t.a==1 and t.b==3 and t.c==2 and t.d==4 and t.e==-1
```

**Comment by mpariente** [comment]
Actually, this doesn't work.. I only checked `d` and `e`. That's what happens when I shout victory before running the tests, sorry. 

So, actually, is there a way to do that without having to write `store_attr(a=a, b=b, c=c, **kwargs)`?

**Comment by mpariente** [comment]
Cc @jph00 @hamelsmu please

**Comment by hamelsmu** [comment]
The best way to accomplish this immediately is like this 

```py
from fastcore.all import *

class T:
    def __init__(self, a,b,c,**kwargs): 
        store_attr('a,b,c')
        store_attr(**kwargs)

t = T(1,c=2,b=3,d=4,e=-1)
assert t.a==1 and t.b==3 and t.c==2 and t.d==4 and t.e==-1
```

I'll open a separate feature request issue

However, we may consider adding direct support for this in the future.
