### ISSUE TITLE
Why does `fastuple` return `(<map at 0x7f79d0fee7d0>)`

### ISSUE THREAD

**Issue by amaarora** [fastai/fastcore#212]
To replicate: 

https://gist.github.com/amaarora/4aafc1f6a298a41e0b10bd00aaf8720c

We do not raise a `TypeError` here: `except TypeError: x = (x,)`  but rather convert the map function to a tuple.

And so the map function get's converted to `(<map at 0x7f79d0fee7d0>)` which then finally get's returned. 

Is this expected behaviour?

**Comment by hamelsmu** [comment]
I don't really understand what you are trying to do?  I believe this is the way you are supposed to use this interface:

![image](https://user-images.githubusercontent.com/1483922/102719896-8d254880-42a5-11eb-9ee7-2563c7f7ffcd.png)

Let me know

**Comment by hamelsmu** [comment]
@amaarora I see you gave my answer a thumbs up :) I'll go ahead and close this issue, but please let me know if this did not answer your question.
