### ISSUE TITLE
TypeError with progress=True in fastcore.parallel.parallel

### ISSUE THREAD

**Issue by dansbecker** [fastai/fastcore#256]
I'd installed fastcore 1.3.12 but hadn't installed fastprogress and then ran the following
```
def return_one(i):
    return 1
parallel(f=return_one, items=range(5), n_workers=2, progress=True)
```

This leads to a stack trace
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-25-4910dc0c904f> in <module>
      3 def return_one(i):
      4     return 1
----> 5 parallel(f=return_one, items=range(5), n_workers=2, progress=True)

~/anaconda3/envs/python3/lib/python3.6/site-packages/fastcore/parallel.py in parallel(f, items, n_workers, total, progress, pause, threadpool, timeout, chunksize, *args, **kwargs)
    104         if progress:
    105             if total is None: total = len(items)
--> 106             r = progress_bar(r, total=total, leave=False)
    107         return L(r)
    108 

TypeError: 'NoneType' object is not callable
```

I believe there is an error in [this line](https://github.com/fastai/fastcore/blob/master/fastcore/parallel.py#L100) in that it calls us to reach 106 even if `progress_bar` is `None`

I'll submit a patch for this as well

**Comment by hamelsmu** [comment]
@jph00 is fastprogress meant to be a dependency of fastcore?  I also have to look into why this is not being caught in CI

**Comment by jph00** [comment]
fastprogress isn't a dep - it's only meant to be used if available.

I'll close this since there's a PR to fix it now.
