### ISSUE TITLE
Possibly missing '_is_first' in fastcore/xtras.py

### ISSUE THREAD

**Issue by moaazsidat** [fastai/fastcore#272]
On running 
``` 
learn = cnn_learner(dls, resnet18)
```
as part of [06_multicat](https://colab.research.google.com/github/fastai/fastbook/blob/master/06_multicat.ipynb), first line of code in the **Binary Cross-Entropy** section, running into a 
```
/usr/local/lib/python3.6/dist-packages/fastcore/xtras.py in sort_by_run(fs)
    377     while len(inp):
    378         for i,o in enumerate(inp):
--> 379             if _is_first(o, inp):
    380                 res.append(inp.pop(i))
    381                 break

NameError: name '_is_first' is not defined
```

Possibly related to the most recent change made an hour ago? https://github.com/fastai/fastcore/commit/b82d56a01ec316e599e00b0971d6a35f33c11a52#diff-cf82fbb92637bba952dd4c48f96a2439b2d3d33b8876e4d4817186a78effb3bdR379-R383

cc @jph00

**Comment by ALCarter2** [comment]
I believe that _is_instance is also missing as well.

**Comment by aaronnguyen** [comment]
Can also confirm, both _is_first and _is_instance are missing.

As a work around, I just copied the functions from an old fastcore/utils.py and pasted them into fastcore/xtras.py and it worked for me.

**Comment by jph00** [comment]
Many apologies! Fixed now
