### ISSUE TITLE
Feature request: Optional arguments for the to-be-tested function in `test_fail`

### ISSUE THREAD

**Issue by michaelaye** [fastai/fastcore#285]
The code of `fastcore.test.test_fail` shows that it only calls the provided function without any parameters.
It would be nice to be able to directly provide parameters to the function to test that it fails for some parameters.
In code:

```python
def f(a):
    if a == 5:
        raise ValueError
```
and I would like to force this failure for testing by using something like `test_fail(f, args=(5,))`

**Comment by Salehbigdeli** [comment]
The feature is added and this issue should close :)
