### ISSUE TITLE
Bug - test_eq on list to array returns attribute error not assertion error

### ISSUE THREAD

**Issue by sambo55** [fastai/fastcore#288]
Index.ipynb

Testing

When a test fails, it prints out information about what was expected:

`test_eq([0,1,2,3], np.arange(3))`

returns attribute error instead of assertion error shown in the example

[0,1,2,3] == np.arange(3) returns boolean False which has no attribute 'all'

Not sure best way to fix, could simply add

`if len(a) != len(b): return False`

to the equals function in imports

Thanks

**Comment by tcapelle** [comment]
I don't have this issue:
![image](https://user-images.githubusercontent.com/18441985/109714704-07762100-7ba3-11eb-9824-e1fe7f936eab.png)

**Comment by tcapelle** [comment]
probably a good idea.
