### ISSUE TITLE
Fastcore.script unable to override default arguments when importing

### ISSUE THREAD

**Issue by Chris-hughes10** [fastai/fastcore#290]
Hi,

I have recently been looking at using fastcore.script as a way to create lightweight scripts around functions which are also imported and used elsewhere. However, I seem to be experiencing some odd behaviour, which I will illustrate with a trivial example.

Let’s say I define a script `say_hello_script.py` which contains:
```
from fastcore.script import *


@call_parse
def say_hello(greeting: Param('Greeting', str) = 'Hello',
              name: Param('Name', str) = 'World'):
    print(f'{greeting}, {name}')
```

If I call this from the command line using `python say_hello_script.py --name Chris`, I get the expected output of `Hello, Chris.` All is good so far.

However, now I want to call this function from a different script, so I will create a script `greeter.py` which contains:
```
from say_hello_script import say_hello

if __name__ == '__main__':
    say_hello(greeting='hi', name='person')
```

Running `python greeter.py` I get the output of `Hello, World`, which seems to have bypassed my arguments! Is this the normal behaviour?

Thanks,
Chris

**Comment by tcapelle** [comment]
I had the same issue some time ago. I didn't explored more, but ended up using other [tool](https://github.com/tiangolo/typer).
I think `fastscript` is meant to be used very simply, and this is more than what is it built to.

**Comment by Chris-hughes10** [comment]
Just bumping this as I feel fastcore.script is so close to being great if this issue is resolved; far better than argparse! I don't quite agree that this use case is more that fastscript is meant to do, as it clearly states in the docs:
```
call_parse decorated functions work as regular functions and also as command-line interface functions
```
I would argue that as function arguments are ignored, decorated functions do not work as regular functions.

**Comment by jph00** [comment]
Thanks for the report. Unfortunately this isn't something I could find a way to get working. If you or anyone else figures it out, I'd be happy to take a PR!

**Comment by ChrisRichardMiles** [comment]
I also have run into problems similarly, except I am trying to use a "script function" in another "script function" but get this error: 
```
usage: crm_m5_fe_shifts_momentum [-h] [--path PATH] [--path_json PATH_JSON] [--pdb] [--xtra XTRA]
crm_m5_fe_shifts_momentum: error: unrecognized arguments: --path_features . --path_out_features .
```
crm_m5_fe_shifts_momentum is the outer function with params `path_features`  and `path_out_features` . 
Inside of that function I call `function_2` which has params `path` and `path_json`

Its like the system is trying to use my inputs into the console script as inputs into the every console script that is called inside. 

I will try to figure it out later and make a pull request if I can make it work.

**Comment by Chris-hughes10** [comment]
Hi @jph00, I think I have found how to fix the problem (adding the line `args = merge(args, kwargs)` before `tfunc(**merge(args, args_from_prog(func, xtra)))`). I am happy to submit a PR, but looking for some guidance on how best to test this.

This behaviour only really seems to occur when an annotated function is called from another module, so I am unable to replicate the behaviour in a single notebook to write a test. I could set up another notebook or script to test this, but that will break the paradigm of having all tests and code in the same place. 

What are your thoughts on this?

**Comment by jph00** [comment]
Not sure there's much you can do around automated tests, but that's OK. Just do all the manual tests you can think of to make sure it at least works on your machine.
