### ISSUE TITLE
Feature Request: version of `bind` that preserves signature

### ISSUE THREAD

**Issue by juan-carlos-calvo** [fastai/fastcore#35]
`bind`'s signature after binding a function is `<Signature (*args, **kwargs)>` . Could it be possible to please have a version of it that gives back a function (or bind object) with the right signature after binding? for example:
for `def foo(a: int, b: str, c: float, d: str='hey'): pass`
its signature is `<Signature (a: int, b: str, c: float, d: str = 'hey')>`
and if I define `bf = bind(foo, 1, _Arg(0), 2)`
I would like to have `bf`s signature be `<Signature (b: str, d: str = 'hey')>`

**Comment by sgugger** [comment]
Please use the [forum](https://forums.fast.ai/) for feature requests as we keep the issues for bug only.
