### ISSUE TITLE
When using from fastcore.nb_imports  in a nbs github actions fail. 

### ISSUE THREAD

**Issue by tommichiels** [fastai/fastcore#357]
When using the import from fastcore.nb_imports   in a notebook my standard github actions from the nbdev template fail with the following error.

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.6.14/x64/bin/nbdev_test_nbs", line 8, in <module>
    sys.exit(nbdev_test_nbs())
  File "/opt/hostedtoolcache/Python/3.6.14/x64/lib/python3.6/site-packages/fastcore/script.py", line 107, in _f
    tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/opt/hostedtoolcache/Python/3.6.14/x64/lib/python3.6/site-packages/nbdev/test.py", line 120, in nbdev_test_nbs
    raise Exception(msg + '\n'.join([f.name for p,f in zip(passed,files) if not p]))

Locally this does not give any error so and all my tests run. It is happening on all python versions. 
These are my requirements  = fastcore>=1.3.26 jupyter-client<6.1.13 

These are my imports
import json
import multiprocessing
from formai.utils import extension
from fastcore.test import *
from fastcore.imports import *
from fastcore.nb_imports import *

When I only use these imports it is working 
import json
import multiprocessing
from formai.utils import extension
from fastcore.test import *
from fastcore.imports import *

So probably this combination is not ok.

from fastcore.imports import *
from fastcore.nb_imports import *

error is reproducable locally when I remove 
from fastcore.imports import *

No need for fix but wanted to get you guys a headsup I had these problems as a newbie.

**Comment by jph00** [comment]
Thanks for letting us know. If you (or anyone) finds the underlying cause, please tell us so we can fix it!
