### ISSUE TITLE
fastcore.utils.Tuple shadows typing.Tuple

### ISSUE THREAD

**Issue by indigoviolet** [fastai/fastcore#36]
It surprised me with an unexpected error that `fastcore.utils.Tuple` exists -- it shadows the stdlib's `typing.Tuple`. Should this be renamed to something that doesn't collide with the stdlib, or is this expected?

**Comment by tcapelle** [comment]
it is expected, you can just use this one.

**Comment by sgugger** [comment]
You can always import the original `typing.Tuple` by giving it another name: `from typing import Tuple as OldTuple`.

**Comment by indigoviolet** [comment]
Hi, thanks for the quick responses. 

1) I don't think I can use `fastcore.utils.Tuple` as `typing.Tuple`: see this gist where it breaks: https://gist.github.com/indigoviolet/175556625b9e21748fe2d2be6500a1bb

2) I understand that I can `import typing.Tuple as OldTuple`, but IMHO a library shouldn't shadow a standard library name without a very good reason, and should definitely not break it. I would expect `fastcore.utils.Tuple` to require explicitly importing it if it needs to be named `Tuple`.

**Comment by indigoviolet** [comment]
hey @sgugger , @tcapelle  -- not sure if you saw my comment above after closing this issue..
