### ISSUE TITLE
basics.listify doesn't work as expected on a dict

### ISSUE THREAD

**Issue by danielmitchell** [fastai/fastcore#374]
Running basics.listify() on a dict results in a list of keys rather than a list containing the dict.

For example, `listify({'a': 1, 'b': 2})` -> `['a', 'b']` and not `[{'a': 1, 'b': 2}]`.

My use case is a function that accepts either a single dict or a list of dicts and I wanted to use listify to standardise it to a list.

Is this behavior intentional or can it be changed to match what I'm looking for? I'm happy to create a PR with the change but want to check first whether the change is acceptable.

**Comment by jph00** [comment]
We should leave it as is, since that's how python listifies dicts
