### ISSUE TITLE
`retain_type` does not work with list2tuple

### ISSUE THREAD

**Issue by tcapelle** [fastai/fastcore#376]
Small hidden bug...
```python
retain_type([1,2,3], tuple([1]))
> [1,2,3]
```
it should be:
```python
> (1,2,3)
```

**Comment by Salehbigdeli** [comment]
You want `retain_type(new=[1,2,3], old=tuple([1]))`
I think this isn't a bug and it's what document of the function says!
    "Cast `new` to type of `old` or `typ` if it's a superclass"
I think the other comment in the code can help too:
```python
# e.g. old is TensorImage, new is Tensor - if not subclass then do nothing
```
P.S. You can close this issue if this comments answer your question.

**Comment by tcapelle** [comment]
Shouldn't it cast new ("list") to the type of old ("tuple")

**Comment by Salehbigdeli** [comment]
No, I don't think so. Because `list` is not a subclass of `tuple`.
