### ISSUE TITLE
Why "assert cls.__doc__ is not None" in "foundation.add_docs"

### ISSUE THREAD

**Issue by KushajveerSingh** [fastai/fastcore#38]
When I write the following code, I get an error.

```python
@docs
class A:
    def a(self): ...
    _docs = dict(a='Doc for `a`')
```

This makes sense because I have not specified documentation for the class `A`. So I have to change the code to this

```python
@docs
class A:
    "Doc for class A"
    def a(self): ...
    _docs = dict(a='Doc for `a`')
```

This is happening due to the last assert statement in `fastcore.foundation.add_docs` function i.e. `assert cls.__doc__ is not None, f"Missing class docs: {cls}"`.

My questions are
1. What is the need of this assert statement?
2. When using `@docs` decorator, how to specify the documentation for the class in the `_docs` dict? Like in the above example, how to specify the documentation for class A ('Doc for class A') in the `_docs` dict.
3. Does it make sense to make this assert check optional? Like for the cases when I don't want to write documentation for the main class, but write documentation for the functions in it.

**Comment by jph00** [comment]
The purpose of this is to ensure that all classes are fully documented. That's our desired behavior.
