### ISSUE TITLE
Feature request: .flatten on L module

### ISSUE THREAD

**Issue by mariano22** [fastai/fastcore#393]
A flatten module could be a nice behavior to add to L module.
It's very common to need to flatten a list and a method would much shorter (and prevent error) than doing by yourself all the time.

If you agree I can make a PR to add it. I'm currently using this modification on my code:

`@patch 
def flatten(self:L): return L(x for xs in self for x in xs)`

**Comment by jph00** [comment]
I think you can just do `concat(x)` can't you?

**Comment by mariano22** [comment]
I didn't find L.concat functionality thanks and sorry for opening the issue!
