### ISSUE TITLE
Release 1.4.0 is is breaking on python 3.6

### ISSUE THREAD

**Issue by kptkin** [fastai/fastcore#400]
`fastcore` release 1.4.0 is breaking on python 3.6 with this specific error:
```
python3.6/site-packages/fastcore/dispatch.py", line 4
       from __future__ import annotations
SyntaxError: future feature annotations is not defined
```
- Looking at the commit history it seems that this line was added as part of the new release:
`from __future__ import annotations`  in https://github.com/fastai/fastcore/blob/1.4.0/nbs/04_dispatch.ipynb
- Reading PEP-563 (https://peps.python.org/pep-0563/#enabling-the-future-behavior-in-python-3-7) this is only supported starting from 3.7. From what I understand `fastcore` is supporting 3.6 (according to this: https://pypi.org/project/fastcore/). 
- Is `fastcore` dropping support for 3.6 or is it an actual issue?

**Comment by jph00** [comment]
Python 3.6 is now [past EOL](https://endoflife.date/python) so is no longer supported in fastcore. I apologise for failing to update the version compatibility in pypi - will fix that in next release.
