### ISSUE TITLE
Using fastcore in google cloud function

### ISSUE THREAD

**Issue by takotab** [fastai/fastcore#43]
Hi,

Big fan of the library. I'm only have one issue and want to record it for other people who might come across the same problem.

When using fastcore inside a google cloud function and putting fastcore as a depency in your requirements.txt file you get an error.

I think it has to do with the `dataclasses` library.

Would be nice if it could be fixed. 
Currently I just install numpy and copy the fastcore folder into the root folder.

**Comment by jph00** [comment]
If you post an issue with a reproducible example, error message, and stack trace, then we'll do our best to fix it.
