### ISSUE TITLE
AttrDict

### ISSUE THREAD

**Issue by erlebach** [fastai/fastcore#445]
Consider: 
a = L(3,4)  # a wrapper around a list. b = a.copy()  # copies as expected and b is of type L
Do the same with a dictionary:
a = AttrDict({'a':3, 'b':4})b = a.copy()
b is a regular dict, and not an AttrDict. Is this expected behavior? I had a bug related to this issue. 

Great library by the way.

**Comment by jph00** [comment]
No not what I'd expect as behavior. Feel free to submit a PR if you have a good solution.

**Comment by Salehbigdeli** [comment]
> No not what I'd expect as behavior. Feel free to submit a PR if you have a good solution.

Just submitted a PR for it!
