### ISSUE TITLE
Tag the source

### ISSUE THREAD

**Issue by fabaff** [fastai/fastcore#457]
It would be very helpful if you could tag releases again. This would enable distributions who want to fetch the package from GitHub instead of PyPI.

Tags were present in the past. 

Thanks

**Comment by jph00** [comment]
I thought we are still? I certainly didn't intend to make any changes. I still see releases listed in github -- can you let me know in more detail what you're seeing?

**Comment by fabaff** [comment]
Today: 

GitHub: https://github.com/fastai/fastcore/releases/tag/1.5.15
PyPI: https://pypi.org/project/fastcore/1.5.16/

**Comment by jph00** [comment]
Oh I see what you mean. We tag all releases that we think are worth announcing.
