### ISSUE TITLE
Avoid patching standard library classes (suggestiong/discussion)

### ISSUE THREAD

**Issue by davidgilbertson** [fastai/fastcore#466]
I'm sure this has been considered, but I couldn't see an issue addressing it directly, so I'll create this as a place to discuss.

I think the practice of patching Python's standard library objects (e.g. adding a `.ls` method to `pathlib.Path`) can be quite harmful, the main issues:

* It blocks the language from evolving. This was seen in the web development world (see the link below for more details): a widely used library patched the `Array` object with a useful method. A later change to the language attempted to add that method (because it was useful!), with slightly different behaviour, but early tests showed that it broke a lot of websites, because the offending library was so widely used. So, what if the Python folks want to add `Path.ls` in the future? That means what would otherwise be a non-breaking change, becomes a change that breaks a lot of apps running in production if they include `fastcore`. And the kicker is that the more useful your additions are, the more likely they are to make it into future version of Python. So as the years roll by, fastai becomes even more widely used, and the language evolves you're almost certainly going to cause pain to the Python maintainers and users. It's a practice that's handy in small environments, but doesn't scale with with size or time.
* If everyone did it, there would be clashes. Imagine if `scipy`, `numpy`, `scikit-learn`, etc all also decided that they would all add their own useful methods to `Path`. You would soon get to the point where import order of packages affected runtime behaviour, and in many cases would just break code in a way that is very difficult to troubleshoot.
* Code isn't portable. A user might take some code that uses `path.ls` in a module that imports fastcore (perhaps indirectly) and move it to another module, not realising that `path.ls` isn't standard. Now their code breaks (depending in import order?!) and it's not at all clear why, they just know that now they're being told that `path` has no method `ls`. This makes codebases extraordinarily brittle as you move beyond the simple case of a Jupyter notebook into a fully fledged, modular application.

Further reading:
* A few issues in the repo already caused by this (https://github.com/fastai/fastcore/issues/95, https://github.com/fastai/fastcore/issues/29)
* [Wikipedia has a section on when/why monkey-patching is a bad idea](https://en.wikipedia.org/wiki/Monkey_patch#Pitfalls)
* The title of this article says it all: [Don't modify objects you don't own](https://humanwhocodes.com/blog/2010/03/02/maintainable-javascript-dont-modify-objects-you-down-own/) (it's about JavaScript, but the logic is the same)

**Comment by jph00** [comment]
Yes we have discussed this a number of times, and decided that in this particular case the benefits outweigh the drawbacks.

- If Python in the future adds Path.ls, we will remove ours. This would break existing usages of Path.ls if the python version isn't compatible, which would be annoying. However, if we remove Path.ls now, it will break existing usages with 100% chance immediately, rather than there being a small probability that this might happen some time in the future
- Path.ls is designed for interactive use. There's very little reason to use it ourside of a REPL
- If someone uses a function without knowing what it is or where it comes from, that's on them, frankly!
