### ISSUE TITLE
Changes in 1.5.23 break nbdev cli

### ISSUE THREAD

**Issue by angus-g** [fastai/fastcore#477]
With the 1.5.23 release, running `nbdev_new` or `nbdev_create_config` gives an error like the following:

```
nbdev_new: error: the following arguments are required: cfg
```

Seems like something may have broken with `delegates` parameter exclusion?

**Comment by seeM** [comment]
I'm not getting this issue with latest `master` of nbdev and fastcore. Could you please try with that?
