### ISSUE TITLE
L.split() is not the same as `str.split`

### ISSUE THREAD

**Issue by prairie-guy** [fastai/fastcore#54]
I’m not sure if posts like this belong on forum or here. (I looked for guidance in the forums, but probably missed it.)
Love what you have done with `fastcore`. As a long time devote of the lisp style of languages, the addition of the `L` type is great!. I have just started playing around with it and found the following differences between `L.split()` and `str.split()`. Since the doc-string in L says they should behave the same, I bring this to your attention:

——————————————————————————-
```py
In [68]: a = "this is a test of the thing"                                                                                                            

In [69]: a.split?                                                                                                                                     
Signature: a.split(sep=None, maxsplit=-1)
Docstring:
Return a list of the words in the string, using sep as the delimiter string.

sep
  The delimiter according which to split the string.
  None (the default value) means split according to any whitespace,
  and discard empty strings from the result.
maxsplit
  Maximum number of splits to do.
  -1 (the default value) means no limit.
Type:      builtin_function_or_method

In [70]: a.split()                                                                                                                                    
Out[70]: ['this', 'is', 'a', 'test', 'of', 'the', 'thing']

In [71]: a.split(' ')                                                                                                                                 
Out[71]: ['this', 'is', 'a', 'test', 'of', 'the', 'thing']

In [72]: a.split('t')                                                                                                                                 
Out[72]: ['', 'his is a ', 'es', ' of ', 'he ', 'hing']

In [73]: b = L(a)                                                                                                                                     

In [74]: b.split?                                                                                                                                     
Signature: b.split(s, sep=None, maxsplit=-1)
Docstring: Same as `str.split`, but returns an `L`
File:      ~/anaconda3/envs/fastai/lib/python3.8/site-packages/fastcore/foundation.py
Type:      method

In [75]: b.split()                                                                                                                                    
TypeError                                 Traceback (most recent call last)
<ipython-input-75-5540ebcda3d0> in <module>
----> 1 b.split()

TypeError: split() missing 1 required positional argument: 's'

In [76]: b.split(' ')                                                                                                                                 
Out[76]: (#0) []

In [77]: b.split('t')                                                                                                                                 
Out[77]: (#1) ['t']
```

**Comment by hamelsmu** [comment]
I'm going to format your ☝️ message so I can read the code

**Comment by hamelsmu** [comment]
@prairie-guy that particular method calls the split method on the object that you pass in (which should be a string), and is the equivalent of calling `str.split()` on something [per the docs](https://fastcore.fast.ai/foundation.html#L.split).   This is class method not an instance method so it is not meant to operate on the instance `b` in your example above

cc: @jph00 should I try to somehow differentiate these class methods from the instance methods in the docs?   What do you think?

**Comment by jph00** [comment]
> cc: @jph00 <https://github.com/jph00> should I try to somehow differentiate these class methods from the instance methods in the docs? What do you think?


Not sure that always quite fits - you really want to have similar methods together, and sometimes class and instance are similar. I think mention in the docstring it's a class method, and ensure there are clear examples.

**Comment by prairie-guy** [comment]
My two cents—as a fresh user to fastai2, but an alumni multiple previous courses—is that a designation in the doc string would be great. I like learning by just trying things out in the REPL. I was fascinated with the new ‘L’ type and was using tab-completion and the doc strings to get my head around what it’s all about. That’s how I bumped into this question.

**Comment by hamelsmu** [comment]
I'll resolve this issue, assigning it to myself
