### ISSUE TITLE
Allow urlsend to accept and pass decode flag to urlrequest

### ISSUE THREAD

**Issue by radam9** [fastai/fastcore#608]
Hey there,

This issue was already brought up in the following issue https://github.com/fastai/fastcore/issues/304 and was resolved.

Unfortunately the solution only fixed the issue for a specific endpoint in ghapi only, other endpoints like in this ticket https://github.com/fastai/ghapi/issues/157 or this one [fastai/ghapi/metadata.py#L1027](https://github.com/fastai/ghapi/blob/4fe9459c7e7bd631c7317eaa9d2365f14f2cb34d/ghapi/metadata.py#L1027) don't have a `archive_format` parameter in the url, and thus it ends up failing when trying to decode the response.

To me it seems like the initial solution suggested here https://github.com/fastai/fastcore/issues/304 of accepting the `decode` parameter in `urlsend` is a more generic solution.
This would not be the entire solution as some changes will still need to be implemented on the ghapi's side to actually send the `decode` argument when needed.

**Comment by jph00** [comment]
I'm happy to look at a PR with a more general solution.
