### ISSUE TITLE
AttributeError: 'str' object has no attribute '__stored_args__' 

### ISSUE THREAD

**Issue by binarymason** [fastai/fastcore#70]
As mentioned in https://github.com/fastai/fastai/issues/2758, looks like https://github.com/fastai/fastcore/commit/ea1c33f1c3543e6e4403b1d3b7702a98471f3515#diff-2d5ca7a202ff50e2df29f58cfa4a4c12 may have introduced a bug.

Thanks for the great library!

**Comment by jph00** [comment]
Thanks for filing this issue. I think it's that I forgot to do a release of fastcore. Will do that now.

**Comment by aviogit** [comment]
I'm still having the problem with fastcore 1.0.13 and fastai 2.0.13 (sorry for the duplicate here: https://github.com/fastai/fastai/issues/2758).
