### ISSUE TITLE
wrong assert in "test_eq_type". It checks if two values are equal. The type is checked after that

### ISSUE THREAD

**Issue by NorbertH14** [fastai/fastcore#76]
https://github.com/fastai/fastcore/blob/7ac3fc26f3732148795ac7680f394737f87e600f/fastcore/test.py#L39

the marked line should be deleted

thanks a lot

test_eq_type(1, 2)

======== stacktrace begin
HERE---> 39     test_eq(a,b)
     40     test_eq(type(a),type(b))
     41     if isinstance(a,(list,tuple)): test_eq(map(type,a),map(type,b))

~/anaconda3/envs/etftrader/lib/python3.7/site-packages/fastcore/test.py in test_eq(a, b)
     32 def test_eq(a,b):
     33     "`test` that `a==b`"
---> 34     test(a,b,equals, '==')
     35 
     36 # Cell

~/anaconda3/envs/etftrader/lib/python3.7/site-packages/fastcore/test.py in test(a, b, cmp, cname)
     22     "`assert` that `cmp(a,b)`; display inputs and `cname or cmp.__name__` if it fails"
     23     if cname is None: cname=cmp.__name__
---> 24     assert cmp(a,b),f"{cname}:\n{a}\n{b}"
     25 
     26 # Cell

AssertionError: ==:
1
2
======== stacktrace end

**Comment by jph00** [comment]
Read the docstring
