### ISSUE TITLE
fastcore not working properly on Windows

### ISSUE THREAD

**Issue by rladeira** [fastai/fastcore#89]
I tried to install fastcore on a Windows machine, and couldn't make it work as showcased in the documentation. The installation does finish without errors, but it seems that the inner modules of the package are not accessible, as if the package is empty.

Installation commands (python 3.6 is a requirement that I have):

```bash
conda create -n env_fastcore python=3.6
conda activate env_fastcore 
conda install -c fastai fastcore
```

Simple commands that I tried to execute:

```python
In [1]: import fastcore

In [2]: fastcore.__version__
Out[2]: '1.0.12'

In [3]: fastcore.utils
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-7f4bf76169d5> in <module>
----> 1 fastcore.utils

AttributeError: module 'fastcore' has no attribute 'utils'

In [4]: dir(fastcore)
Out[4]:
['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__']
```

Any hints on how to configure it properly?

**Comment by rladeira** [comment]
Interestingly, the following construct works:

```python
In [1]: from fastcore.utils import L

In [2]: 1 + L.range(2, 5)
Out[2]: (#4) [1,2,3,4]
```

So, the installation seems to be OK. The issue is related to which commands are used to import the inner functions and classes of the fastcore package. I thought that ```import fastcore; fastcore.utils.L``` should also work, but that's not the case.

**Comment by JunnYu** [comment]
I add these import codes  into "__init__.py" and it works.
![image](https://user-images.githubusercontent.com/50394665/93667740-b70a7b80-faba-11ea-89f4-ff878db9dfbb.png)

**Comment by jph00** [comment]
Yup, you have to import the submodules you want.
