### ISSUE TITLE
Unexpected behavior of cycle (and everything using _listify)

### ISSUE THREAD

**Issue by kessido** [fastai/fastcore#99]
As far as I know, I would have expected cycle to work with np.array as it would work with itertool.cycle

```
>>> from fastcore.foundation import cycle
>>> import numpy as np
>>> it = cycle(np.arange(3))
>>> next(it)
array([0, 1, 2])
>>> next(it)
array([0, 1, 2])
>>> next(it)
array([0, 1, 2])
```

```
>>> from itertools import cycle
>>> import numpy as np
>>> it = cycle(np.arange(3))
>>> next(it)
0
>>> next(it)
1
>>> next(it)
2
```

solution: IMO _listify should return o instead of [o]

**Comment by jph00** [comment]
Well... it's a bit of a tough choice. Generally arrays and tensors are considered as single items in most stuff we do. So the current behavior is as-intended. It's possible not sufficiently well documented, however...
